# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d6f557de34d6e29efcf2194d2f5bdc16869c112d01df956134cc1db21f2e57c3ff2db855caf9d05ae719cc88dfc305a63b19c3d70f026745261e97454362028

test:
  secret_key_base: dfd8aa3ecca8fbc467dd562d5a4604204f272fc6b081a393f48b8785df27cfbcb09f36f267074f8ed13e37282e0ef2b07adc6d1d7a1b5e2156b54f370605acec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
